export const buttons = [
  { id: 'nine',
    val: '9', 
    func: 'handleNumberClick'},
  { id: 'eight',
    val: '8', 
    func: 'handleNumberClick'},
  { id: 'seven',
    val: '7', 
    func: 'handleNumberClick'},
  { id: 'six',
    val: '6', 
    func: 'handleNumberClick'},
  { id: 'five',
    val: '5', 
    func: 'handleNumberClick'},
  { id: 'four',
    val: '4', 
    func: 'handleNumberClick'},
  { id: 'three',
    val: '3', 
    func: 'handleNumberClick'},
  { id: 'two',
    val: '2', 
    func: 'handleNumberClick'},
  { id: 'one',
    val: '1', 
    func: 'handleNumberClick'},
  { id: 'zero',
    val: '0', 
    func: 'handleNumberClick'},
  { id: 'decimal',
    val: '.', 
    func: 'handleDotClick'}
];

